version: "3.7"

services:
    proxy:
        image: nginx
        volumes: 
            - ./server/proxy/nginx/conf.d:/etc/nginx/conf.d:z
            - ./server/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:z
        restart: always
        ports: 
            - 80:80
            - 443:443
        networks: 
            - backend
            
    api:
        build: ./server/api
        restart: always
        volumes: 
            - ./server/api:/var/www/api
        command: pypy3 manage.py runserver 0.0.0.0:8000
        environment: 
            PYTHONUNBUFFERED: 1
            DB_PASSWORD: password
            DB_USER: cymol
            DB_NAME: database
            DB_HOST: 172.25.20.30
            DB_PORT: 5432    
        networks: 
            backend:
                ipv4_address: 172.35.10.20
            db:
               ipv4_address: 172.25.20.12
        depends_on: 
            - postgres

    postgres:
        image: postgres:alpine
        restart: always
        volumes: 
            - ./server/database/postgres/data:/var/lib/postgresql/data:z
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: cymol
            POSTGRES_DB: database
        networks: 
            db:
                ipv4_address: 172.25.20.30
        

networks:     
    backend:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.35.10.1/16
    db:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.25.20.1/16
    