version: "3.7"

services:
    proxy:
        image: nginx
        volumes: 
            - ./server/proxy/nginx/conf.d:/etc/nginx/conf.d
            - ./server/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        ports: 
            - 80:80
            - 443:443
        networks: 
            - backend

    gateway: 
        build:
            context: ./server/api/gateway/
            dockerfile: Dockerfile.dev
        restart: always
        command: npm start
        volumes: 
            - ./server/api/gateway:/code
        networks: 
            backend:
                ipv4_address: 172.35.10.10
            db:
                ipv4_address: 172.25.20.10
        depends_on: 
            - proxy
            - mongo
            - auth
            - build_gateway

    build_gateway: 
        build:
            context: ./server/api/gateway/
            dockerfile: Dockerfile.dev
        restart: always
        command: npx tsc -w
        volumes: 
            - ./server/api/gateway:/code        

    mongo:
        image: mongo
        restart: always
        volumes: 
            - ./server/database/mongo/data:/data/db:rw
        networks: 
            db:
                ipv4_address: 172.25.20.20

    mongo-manager:
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: 172.25.20.20
        depends_on: 
            - mongo
        networks: 
            db:
                ipv4_address: 172.25.20.50
            
    auth:
        build: 
            context: ./server/api/auth/
            dockerfile: Dockerfile.dev
        command: python manage.py runserver 0.0.0.0:8000
        restart: always
        volumes: 
            - ./server/api/auth:/code
        environment: 
            DB_PASSWORD: password
            DB_USER: cymol
            DB_NAME: database
            DB_HOST: 172.25.20.30
            DB_PORT: 5432    
        networks: 
            backend:
                ipv4_address: 172.35.10.20
            db:
               ipv4_address: 172.25.20.12
        depends_on: 
            - postgres

    postgres:
        image: postgres:alpine
        restart: always
        volumes: 
            - ./server/database/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: cymol
            POSTGRES_DB: database
        networks: 
            db:
                ipv4_address: 172.25.20.30
        

networks:     
    backend:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.35.10.1/16
    db:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.25.20.1/16
    