version: "3.7"

services:
    proxy:
        image: nginx
        volumes: 
            - ./server/proxy/nginx/conf.d:/etc/nginx/conf.d
            - ./server/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
            - 443:443
        networks: 
            - backend

    gateway: 
        build:
            context: ./server/api/gateway/
            dockerfile: Dockerfile.dev
        command: npm run test
        volumes: 
            - ./server/api/gateway:/code
        networks: 
            backend:
                ipv4_address: 172.35.10.10
            
    auth:
        build: 
            context: ./server/api/auth/
            dockerfile: Dockerfile.dev
        command: ./manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./server/api/auth:/code
        networks: 
            backend:
                ipv4_address: 172.35.10.20

networks:     
    backend:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.35.10.1/16
    db:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.25.20.1/16
    