version: "3.7"

services:
    proxy:
        image: nginx
        volumes: 
            - ./server/proxy/nginx/conf.d:/etc/nginx/conf.d
            - ./server/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
            - 443:443
        networks: 
            - backend

    gateway: 
        build:
            context: ./server/api/gateway/
            dockerfile: Dockerfile.dev
        command: npm start
        volumes: 
            - ./server/api/gateway:/code
        networks: 
            backend:
                ipv4_address: 172.35.10.10
            db:
                ipv4_address: 172.25.20.10
        depends_on: 
            - proxy
            - mongo
            - build_gateway

    build_gateway: 
        build:
            context: ./server/api/gateway/
            dockerfile: Dockerfile.dev
        command: npx tsc -w
        volumes: 
            - ./server/api/gateway:/code        

    mongo:
        image: mongo
        restart: always
        volumes: 
            - ./server/database/mongo/data:/data/db:rw        
        networks: 
            db:
                ipv4_address: 172.25.20.20

    mongo-manager:
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: 172.25.20.20
        depends_on: 
            - mongo
        networks: 
            db:
                ipv4_address: 172.25.20.50
            
    auth:
        build: 
            context: ./server/api/auth/
            dockerfile: Dockerfile.dev
        command: ./manage.py runserver 0.0.0.0:8000 --insecure
        volumes: 
            - ./server/api/auth:/code
        networks: 
            backend:
                ipv4_address: 172.35.10.20
        depends_on: 
            - gateway

networks:     
    backend:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.35.10.1/16
    db:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.25.20.1/16
    