# Generated by Django 3.1.1 on 2020-09-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'wish', 'verbose_name_plural': 'wishes'},
        ),
    ]
